import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { RequestProvider } from '@/contexts/RequestContext'
import ToastProvider from '@/contexts/toast'
import { AuthProvider } from '@/contexts/useAuth'
import ToastComponent from '@/components/ToastComponent'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SQL Octopus',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <RequestProvider>
            <ToastProvider>
              {children}
              <ToastComponent />
            </ToastProvider>
          </RequestProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
